name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: List current folder
        run: ls -la
