name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: docker version
        run: docker --version
      - name: flask version
        run: flask --version
      - name: coverage version
        run: coverage --version
