name: Run tests on any Push event
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run and check
        run: python calculator.py
      - name: Check out calculator tests
        run: python test.py
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: setup compiler
        run: pip install pyinstaller
      - name: compile to package
        run: pyinstaller calculator.py  --onefile --console
      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>" 
      - name: Commit files
        run: | 
          git add dist/calculator
          git commit -m 'Changes pushed by GitHub Actions' || true
          git push origin master

